<?php

/**
 * @file social_wall.module
 * TODO: Enter file description here.
 */

use Lns\SocialFeed\Provider\InstagramTagProvider;
use Lns\SocialFeed\Provider\InstagramUserMediaProvider;
use Lns\SocialFeed\Client\InstagramApiClient;
use Lns\SocialFeed\Factory\InstagramPostFactory;

/**
 * Implements hook_social_wall_providers.
 */
function social_wall_instagram_social_wall_providers() {
  $postFactory = new InstagramPostFactory();

  $settings = variable_get('social_wall_instagram_settings');

  if (!$settings) {
    return array();
  }

  $instagramAuth = variable_get('social_wall_instagram_auth', array());

  $token = social_wall_instagram_get_access_token();

  if (!isset($token)) {
    return array();
  }

  $client = new InstagramApiClient($token);

  $provider = new InstagramUserMediaProvider($client, $postFactory);

  return array(
    new InstagramTagProvider($client, $postFactory),
    new InstagramUserMediaProvider($client, $postFactory)
  );
}

/**
 * Implements hook_menu().
 */
function social_wall_instagram_menu() {
  $items['admin/config/social_wall/instagram'] = array(
    'title'            => 'Instagram',
    'description'      => 'Instagram page configuration',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('social_wall_instagram_admin_settings'),
    'access arguments' => array('administer social_wall configuration'),
    'file'             => 'social_wall_instagram.admin.inc',
    'file path'        => drupal_get_path('module', 'social_wall_instagram'),
  );

  $items['admin/config/social_wall/instagram/connect'] = array(
    'title'            => 'Instagram',
    'description'      => 'Instagram page configuration',
    'page callback'    => 'social_wall_instagram_connect',
    'access callback'  => TRUE,
    'file'             => 'social_wall_instagram.admin.inc',
    'file path'        => drupal_get_path('module', 'social_wall_instagram'),
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_wall_instagram_preprocess_social_wall_card(&$variables) {
  if($variables['post'] instanceof \Lns\SocialFeed\Model\InstagramPost) {
    $variables['type'] = 'instagram';
  }
}

function social_wall_instagram_social_wall_post_types() {
  return array(
    'instagram' => 'Lns\SocialFeed\Model\InstagramPost'
  );
}

function social_wall_instagram_get_token_provider($store) {

  $social_wall_instagram_settings = variable_get('social_wall_instagram_settings');

  if (!$social_wall_instagram_settings) {
    return null;
  }

  $redirectUrl = url('admin/config/social_wall/instagram/connect', array('absolute' => true));

  $provider = new \Lns\SocialFeed\Client\InstagramTokenProvider(
    $social_wall_instagram_settings['client_key'],
    $social_wall_instagram_settings['client_secret'],
    $redirectUrl,
    $store
  );

  return $provider;
}

function social_wall_instagram_get_access_token() {
  $instagramAuth = variable_get('social_wall_instagram_auth', array());

  return isset($instagramAuth['token']) ? $instagramAuth['token'] : null;
}
