<?php

/**
 * @file social_wall.module
 * TODO: Enter file description here.
 */

use Lns\SocialFeed\Source\MixedSource;
use Lns\SocialFeed\SocialFeed;

/**
 * Implements hook_menu().
 */
function social_wall_menu() {

  $items['admin/config/social_wall'] = array(
    'title' => 'Social wall configuration',
    'description' => 'Bluelink configuration',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer social_wall configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function social_wall_block_info() {
  $blocks['social_wall'] = array(
    'info' => t('Social wall'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_init().
 */
function social_wall_init() {
  require_once DRUPAL_ROOT . '/vendor/autoload.php';

  foreach(social_wall_get_mixed_providers()->getFeed() as $item) {
    echo '<pre>';
    echo $item->getMessage();
    echo '</pre>';
  }

}

function social_wall_get_feed()
{
  $socialFeed = new SocialFeed();

  drupal_alter('social_wall_social_feed', $socialFeed);

  return $socialFeed->getFeed();
}

function social_wall_get_provider($name)
{
  $providers = social_wall_get_providers();

  return $providers[$name];
}

function social_wall_get_providers() {

  static $providers;
  if (!isset($providers)) {
    $providers = &drupal_static(__FUNCTION__);
  }

  $providers = array();

  $nonIndexedProviders = module_invoke_all('social_wall_providers');

  foreach($nonIndexedProviders as $provider) {
    $providers[$provider->getName()] = $provider;
  }

  return $providers;
}
