<?php

/**
 * @file social_wall.module
 * TODO: Enter file description here.
 */

use Lns\SocialFeed\Provider\FacebookPagePostsProvider;
use Lns\SocialFeed\Client\FacebookApiClient;
use Lns\SocialFeed\Factory\PostFactory;

function social_wall_facebook_social_wall_providers() {
  $postFactory = new PostFactory();

  $settings = variable_get('social_wall_facebook_settings');

  $client = new FacebookApiClient($settings['client_key'], $settings['client_secret']);

  return new FacebookPagePostsProvider($client, $postFactory);
}

/**
 * Implements hook_menu().
 */
function social_wall_facebook_menu() {
  $items['admin/config/social_wall/facebook'] = array(
    'title'            => 'Facebook',
    'description'      => 'Facebook page configuration',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('social_wall_facebook_admin_settings'),
    'access arguments' => array('administer social_wall configuration'),
    'file'             => 'social_wall_facebook.admin.inc',
    'file path'        => drupal_get_path('module', 'social_wall_facebook'),
  );

  return $items;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_wall_facebook_preprocess_social_wall_card(&$variables) {
  if($variables['post'] instanceof \Lns\SocialFeed\Model\FacebookPost) {
    $variables['type'] = 'facebook';
  }
}
