<?php

/**
 * @file social_wall_twitter.module
 * TODO: Enter file description here.
 */

use Lns\SocialFeed\Provider\TwitterSearchApiProvider;
use Lns\SocialFeed\Provider\TwitterStatusesLookupApiProvider;
use Lns\SocialFeed\Provider\Twitter;
use Lns\SocialFeed\Client\TwitterApiClient;
use Lns\SocialFeed\Factory\PostFactory;

/**
 * Implements hook_menu().
 */
function social_wall_twitter_menu() {
  $items['admin/config/social_wall/twitter'] = array(
    'title'            => 'twitter',
    'description'      => 'Twitter page configuration',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('social_wall_twitter_admin_settings'),
    'access arguments' => array('administer social_wall configuration'),
    'file'             => 'social_wall_twitter.admin.inc',
    'file path'        => drupal_get_path('module', 'social_wall_twitter'),
  );

  return $items;
}

function social_wall_twitter_social_wall_providers() {

  $postFactory = new PostFactory();
  $settings = variable_get('social_wall_twitter_settings');

  $client = new TwitterApiClient($settings['consumer_key'], $settings['consumer_secret']);

  return array(
    new TwitterSearchApiProvider($client, $postFactory),
    new TwitterStatusesLookupApiProvider($client, $postFactory)
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_wall_twitter_preprocess_social_wall_card(&$variables) {
  if($variables['post'] instanceof \Lns\SocialFeed\Model\Tweet) {
    $variables['type'] = 'twitter';
  }
}

